//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop
#include "Unit1.h"
#include "Unit2.h"
#include "Unit3.h"
//---------------------------------------------------------------------------
#pragma package(smart_init)
#pragma resource "*.dfm"
#include "userinfo.h"
#include <vector>
#include <string>
#include <iostream>
TForm2 *Form2;
HINSTANCE MyCards;
//---------------------------------------------------------------------------
class Card {
public:
    int id;
	AnsiString name;
	AnsiString comment;
	~Card(){};
};
int Scrollmax=0;
int ScrollmaxS=0;
__fastcall TForm2::TForm2(TComponent* Owner)
	: TForm(Owner)
{
	ScrollS->Hide();
    Xuser->Active=true;
	_di_IXMLcollectedType User = Getcollected(Xuser);
	Background->SendToBack();
	MyCards=LoadLibraryA("cards.dll");
	if(!MyCards) {
		ShowMessage("Cards not found!");
		return;
	}
	if(User->Count==0) {
        Form2->Close();
	}
	else {
		if(User->Count<8) {
			Scroll->Hide();
			int condition=User->Count%8;
			switch (condition) {
			case 1:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
				Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
				Card2->Hide();
				Card3->Hide();
				Card4->Hide();
				Card5->Hide();
				Card6->Hide();
				Card7->Hide();
				Card8->Hide();
                Card2D->Hide();
				Card3D->Hide();
				Card4D->Hide();
				Card5D->Hide();
				Card6D->Hide();
				Card7D->Hide();
				Card8D->Hide();
				return;
			case 2:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-7]->id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
				Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-7]->name;
				Card2D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-7] ->comment);
				Card3->Hide();
				Card4->Hide();
				Card5->Hide();
				Card6->Hide();
				Card7->Hide();
				Card8->Hide();
				Card3D->Hide();
				Card4D->Hide();
				Card5D->Hide();
				Card6D->Hide();
				Card7D->Hide();
				Card8D->Hide();
				return;
			case 3:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-7]->id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-6]->id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
				Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-7]->name;
				Card2D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-7] ->comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-6]->name;
				Card3D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-6] ->comment);
				Card4->Hide();
				Card5->Hide();
				Card6->Hide();
				Card7->Hide();
				Card8->Hide();
				Card4D->Hide();
				Card5D->Hide();
				Card6D->Hide();
				Card7D->Hide();
				Card8D->Hide();
				return;
			case 4:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-7]->id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-6]->id);
				Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-5]->id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
				Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-7]->name;
				Card2D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-7] ->comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-6]->name;
				Card3D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-6] ->comment);
				Card4D->Items->Clear();
				Card4D->Items->Add();
				Card4D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-5]->name;
				Card4D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-5] ->comment);
				Card5->Hide();
				Card6->Hide();
				Card7->Hide();
				Card8->Hide();
				Card5D->Hide();
				Card6D->Hide();
				Card7D->Hide();
				Card8D->Hide();
				return;
			case 5:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-7]->id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-6]->id);
				Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-5]->id);
				Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-4]->id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
				Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-7]->name;
				Card2D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-7] ->comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-6]->name;
				Card3D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-6] ->comment);
				Card4D->Items->Clear();
				Card4D->Items->Add();
				Card4D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-5]->name;
				Card4D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-5] ->comment);
				Card5D->Items->Clear();
				Card5D->Items->Add();
				Card5D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-4]->name;
				Card5D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-4] ->comment);
				Card6->Hide();
				Card7->Hide();
				Card8->Hide();
				Card6D->Hide();
				Card7D->Hide();
				Card8D->Hide();
                return;
			case 6:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-7]->id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-6]->id);
				Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-5]->id);
				Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-4]->id);
				Card6->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-3]->id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
				Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-7]->name;
				Card2D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-7] ->comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-6]->name;
				Card3D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-6] ->comment);
				Card4D->Items->Clear();
				Card4D->Items->Add();
				Card4D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-5]->name;
				Card4D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-5] ->comment);
				Card5D->Items->Clear();
				Card5D->Items->Add();
				Card5D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-4]->name;
				Card5D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-4] ->comment);
				Card6D->Items->Clear();
				Card6D->Items->Add();
				Card6D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-3]->name;
				Card6D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-3] ->comment);
				Card7->Hide();
				Card8->Hide();
				Card7D->Hide();
				Card8D->Hide();
                return;
			case 7:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-7]->id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-6]->id);
				Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-5]->id);
				Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-4]->id);
				Card6->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-3]->id);
                Card7->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-2]->id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
				Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-7]->name;
				Card2D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-7] ->comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-6]->name;
				Card3D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-6] ->comment);
				Card4D->Items->Clear();
				Card4D->Items->Add();
				Card4D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-5]->name;
				Card4D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-5] ->comment);
				Card5D->Items->Clear();
				Card5D->Items->Add();
				Card5D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-4]->name;
				Card5D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-4] ->comment);
				Card6D->Items->Clear();
				Card6D->Items->Add();
				Card6D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-3]->name;
				Card6D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-3] ->comment);
				Card7D->Items->Clear();
				Card7D->Items->Add();
				Card7D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-2]->name;
				Card7D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-2] ->comment);
				Card8->Hide();
				Card8D->Hide();
                return;
			}
		}
		else {
			Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position-1]->id);
			Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position]->id);
			Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position+1]->id);
			Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position+2]->id);
			Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position+3]->id);
			Card6->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position+4]->id);
			Card7->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position+5]->id);
			Card8->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position+6]->id);
			if(User->Count==8) {
                Scroll->Hide();
			}
			else {
				Scrollmax=User->Count/8;
				if(User->Count%8 != 0) {
					Scrollmax++;
				}
				Scroll->Max=Scrollmax;
			}
			Card1D->Items->Clear();
			Card1D->Items->Add();
			Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position-1]->name;
			Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position-1] ->comment);
			Card2D->Items->Clear();
			Card2D->Items->Add();
			Card2D->Items->Item[0]->Caption =  User->card[Scroll->Position]->name;
			Card2D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position] ->comment);
			Card3D->Items->Clear();
			Card3D->Items->Add();
			Card3D->Items->Item[0]->Caption =  User->card[Scroll->Position+1]->name;
			Card3D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position+1] ->comment);
			Card4D->Items->Clear();
			Card4D->Items->Add();
			Card4D->Items->Item[0]->Caption =  User->card[Scroll->Position+2]->name;
			Card4D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position+2] ->comment);
			Card5D->Items->Clear();
			Card5D->Items->Add();
			Card5D->Items->Item[0]->Caption =  User->card[Scroll->Position+3]->name;
			Card5D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position+3] ->comment);
			Card6D->Items->Clear();
			Card6D->Items->Add();
			Card6D->Items->Item[0]->Caption =  User->card[Scroll->Position+4]->name;
			Card6D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position+4] ->comment);
			Card7D->Items->Clear();
			Card7D->Items->Add();
			Card7D->Items->Item[0]->Caption =  User->card[Scroll->Position+5]->name;
			Card7D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position+5] ->comment);
			Card8D->Items->Clear();
			Card8D->Items->Add();
			Card8D->Items->Item[0]->Caption =  User->card[Scroll->Position+6]->name;
			Card8D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position+6] ->comment);
		}
	}
}
void __fastcall TForm2::ScrollChange(TObject *Sender)
{
	MyCards=LoadLibraryA("cards.dll");
	 if(!MyCards) {
		 ShowMessage("cards not found");
		 return;
	 }
	_di_IXMLcollectedType User = Getcollected(Xuser);
	Card1->Show();
	Card2->Show();
	Card3->Show();
	Card4->Show();
	Card5->Show();
	Card6->Show();
	Card7->Show();
	Card8->Show();
	Card1D->Show();
	Card2D->Show();
	Card3D->Show();
	Card4D->Show();
	Card5D->Show();
	Card6D->Show();
	Card7D->Show();
	Card8D->Show();
	int condition=User->Count%8;
	if(Scroll->Position==Scrollmax) {
		switch (condition) {
			case 0:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-7]->id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-6]->id);
				Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-5]->id);
				Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-4]->id);
				Card6->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-3]->id);
				Card7->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-2]->id);
				Card8->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-1]->id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
				Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-7]->name;
				Card2D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-7] ->comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-6]->name;
				Card3D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-6] ->comment);
				Card4D->Items->Clear();
				Card4D->Items->Add();
				Card4D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-5]->name;
				Card4D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-5] ->comment);
				Card5D->Items->Clear();
				Card5D->Items->Add();
				Card5D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-4]->name;
				Card5D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-4] ->comment);
				Card6D->Items->Clear();
				Card6D->Items->Add();
				Card6D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-3]->name;
				Card6D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-3] ->comment);
				Card7D->Items->Clear();
				Card7D->Items->Add();
				Card7D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-2]->name;
				Card7D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-2] ->comment);
				Card8D->Items->Clear();
				Card8D->Items->Add();
				Card8D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-1]->name;
				Card8D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-1] ->comment);
                return;
			case 1:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
				Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
				Card2->Hide();
				Card3->Hide();
				Card4->Hide();
				Card5->Hide();
				Card6->Hide();
				Card7->Hide();
				Card8->Hide();
                Card2D->Hide();
				Card3D->Hide();
				Card4D->Hide();
				Card5D->Hide();
				Card6D->Hide();
				Card7D->Hide();
				Card8D->Hide();
				return;
			case 2:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-7]->id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
				Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-7]->name;
				Card2D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-7] ->comment);
				Card3->Hide();
				Card4->Hide();
				Card5->Hide();
				Card6->Hide();
				Card7->Hide();
				Card8->Hide();
				Card3D->Hide();
				Card4D->Hide();
				Card5D->Hide();
				Card6D->Hide();
				Card7D->Hide();
				Card8D->Hide();
				return;
			case 3:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-7]->id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-6]->id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
				Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-7]->name;
				Card2D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-7] ->comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-6]->name;
				Card3D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-6] ->comment);
				Card4->Hide();
				Card5->Hide();
				Card6->Hide();
				Card7->Hide();
				Card8->Hide();
				Card4D->Hide();
				Card5D->Hide();
				Card6D->Hide();
				Card7D->Hide();
				Card8D->Hide();
				return;
			case 4:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-7]->id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-6]->id);
				Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-5]->id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
				Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-7]->name;
				Card2D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-7] ->comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-6]->name;
				Card3D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-6] ->comment);
				Card4D->Items->Clear();
				Card4D->Items->Add();
				Card4D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-5]->name;
				Card4D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-5] ->comment);
				Card5->Hide();
				Card6->Hide();
				Card7->Hide();
				Card8->Hide();
				Card5D->Hide();
				Card6D->Hide();
				Card7D->Hide();
				Card8D->Hide();
				return;
			case 5:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-7]->id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-6]->id);
				Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-5]->id);
				Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-4]->id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
				Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-7]->name;
				Card2D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-7] ->comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-6]->name;
				Card3D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-6] ->comment);
				Card4D->Items->Clear();
				Card4D->Items->Add();
				Card4D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-5]->name;
				Card4D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-5] ->comment);
				Card5D->Items->Clear();
				Card5D->Items->Add();
				Card5D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-4]->name;
				Card5D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-4] ->comment);
				Card6->Hide();
				Card7->Hide();
				Card8->Hide();
				Card6D->Hide();
				Card7D->Hide();
				Card8D->Hide();
                return;
			case 6:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-7]->id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-6]->id);
				Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-5]->id);
				Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-4]->id);
				Card6->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-3]->id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
				Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-7]->name;
				Card2D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-7] ->comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-6]->name;
				Card3D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-6] ->comment);
				Card4D->Items->Clear();
				Card4D->Items->Add();
				Card4D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-5]->name;
				Card4D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-5] ->comment);
				Card5D->Items->Clear();
				Card5D->Items->Add();
				Card5D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-4]->name;
				Card5D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-4] ->comment);
				Card6D->Items->Clear();
				Card6D->Items->Add();
				Card6D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-3]->name;
				Card6D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-3] ->comment);
				Card7->Hide();
				Card8->Hide();
				Card7D->Hide();
				Card8D->Hide();
                return;
			case 7:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-7]->id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-6]->id);
				Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-5]->id);
				Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-4]->id);
				Card6->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-3]->id);
                Card7->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-2]->id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
				Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-7]->name;
				Card2D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-7] ->comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-6]->name;
				Card3D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-6] ->comment);
				Card4D->Items->Clear();
				Card4D->Items->Add();
				Card4D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-5]->name;
				Card4D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-5] ->comment);
				Card5D->Items->Clear();
				Card5D->Items->Add();
				Card5D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-4]->name;
				Card5D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-4] ->comment);
				Card6D->Items->Clear();
				Card6D->Items->Add();
				Card6D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-3]->name;
				Card6D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-3] ->comment);
				Card7D->Items->Clear();
				Card7D->Items->Add();
				Card7D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-2]->name;
				Card7D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-2] ->comment);
				Card8->Hide();
				Card8D->Hide();
                return;
		}
	}
	else {
    	Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-8]->id);
		Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-7]->id);
		Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-6]->id);
		Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-5]->id);
		Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-4]->id);
		Card6->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-3]->id);
		Card7->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-2]->id);
		Card8->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, User->card[Scroll->Position*8-1]->id);
		Card1D->Items->Clear();
		Card1D->Items->Add();
		Card1D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-8]->name;
		Card1D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-8] ->comment);
		Card2D->Items->Clear();
		Card2D->Items->Add();
		Card2D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-7]->name;
		Card2D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-7] ->comment);
		Card3D->Items->Clear();
		Card3D->Items->Add();
		Card3D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-6]->name;
		Card3D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-6] ->comment);
		Card4D->Items->Clear();
		Card4D->Items->Add();
		Card4D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-5]->name;
		Card4D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-5] ->comment);
		Card5D->Items->Clear();
		Card5D->Items->Add();
		Card5D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-4]->name;
		Card5D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-4] ->comment);
		Card6D->Items->Clear();
		Card6D->Items->Add();
		Card6D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-3]->name;
		Card6D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-3] ->comment);
		Card7D->Items->Clear();
		Card7D->Items->Add();
		Card7D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-2]->name;
		Card7D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-2] ->comment);
		Card8D->Items->Clear();
		Card8D->Items->Add();
		Card8D->Items->Item[0]->Caption =  User->card[Scroll->Position*8-1]->name;
		Card8D->Items->Item[0]->SubItems-> Add(User->card[Scroll->Position*8-1] ->comment);
	}
	FreeLibrary(MyCards);
}
void __fastcall TForm2::HideClick(TObject *Sender)
{
	MyCards=LoadLibraryA("cards.dll");
	 if(!MyCards) {
		 ShowMessage("cards not found");
		 return;
	 }
	_di_IXMLcollectedType User = Getcollected(Xuser);
	std::vector<Card>Scards;
	if(Hide->Checked==true) {
		Scroll->Hide();
		ScrollS->Show();
		ScrollS->Position=1;
		Card1->Show();
		Card2->Show();
		Card3->Show();
		Card4->Show();
		Card5->Show();
		Card6->Show();
		Card7->Show();
		Card8->Show();
		Card1D->Show();
		Card2D->Show();
		Card3D->Show();
		Card4D->Show();
		Card5D->Show();
		Card6D->Show();
		Card7D->Show();
		Card8D->Show();
		for(int i=0;i<User->Count;i++) {
			if(User->card[i]->comment != "Basic") {
				Card temp;
				temp.id=User->card[i]->id;
				temp.name=User->card[i]->name;
				temp.comment=User->card[i]->comment;
				Scards.push_back(temp);
			}
		}
		if(Scards.size()==0) {
			ShowMessage("There are no non-basic Cards in Your Collection!");
            Hide->Checked=false;
		}
		else {
			if(Scards.size()<8) {
				ScrollS->Hide();
				switch (Scards.size()) {
					case 1:
						Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[0].id);
						Card1D->Items->Clear();
						Card1D->Items->Add();
						Card1D->Items->Item[0]->Caption =  Scards[0].name;
						Card1D->Items->Item[0]->SubItems-> Add(Scards[0].comment);
						Card2->Hide();
						Card3->Hide();
						Card4->Hide();
						Card5->Hide();
						Card6->Hide();
						Card7->Hide();
						Card8->Hide();
						Card2D->Hide();
						Card3D->Hide();
						Card4D->Hide();
						Card5D->Hide();
						Card6D->Hide();
						Card7D->Hide();
						Card8D->Hide();
						return;
					case 2:
						Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[0].id);
						Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[1].id);
						Card1D->Items->Clear();
						Card1D->Items->Add();
						Card1D->Items->Item[0]->Caption=Scards[0].name;
						Card1D->Items->Item[0]->SubItems-> Add(Scards[0].comment);
						Card2D->Items->Clear();
						Card2D->Items->Add();
						Card2D->Items->Item[0]->Caption =   Scards[1].name;
						Card2D->Items->Item[0]->SubItems-> Add(Scards[1].comment);
						Card3->Hide();
						Card4->Hide();
						Card5->Hide();
						Card6->Hide();
						Card7->Hide();
						Card8->Hide();
						Card3D->Hide();
						Card4D->Hide();
						Card5D->Hide();
						Card6D->Hide();
						Card7D->Hide();
						Card8D->Hide();
						return;
					case 3:
						Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[0].id);
						Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[1].id);
						Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[2].id);
						Card1D->Items->Clear();
						Card1D->Items->Add();
						Card1D->Items->Item[0]->Caption =  Scards[0].name;
						Card1D->Items->Item[0]->SubItems-> Add(Scards[0].comment);
						Card2D->Items->Clear();
						Card2D->Items->Add();
						Card2D->Items->Item[0]->Caption =  Scards[1].name;
						Card2D->Items->Item[0]->SubItems-> Add(Scards[1].comment);
						Card3D->Items->Clear();
						Card3D->Items->Add();
						Card3D->Items->Item[0]->Caption =  Scards[2].name;
						Card3D->Items->Item[0]->SubItems-> Add(Scards[2].comment);
						Card4->Hide();
						Card5->Hide();
						Card6->Hide();
						Card7->Hide();
						Card8->Hide();
						Card4D->Hide();
						Card5D->Hide();
						Card6D->Hide();
						Card7D->Hide();
						Card8D->Hide();
						return;
					case 4:
						Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[0].id);
						Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[1].id);
						Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[2].id);
						Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[3].id);
						Card1D->Items->Clear();
						Card1D->Items->Add();
						Card1D->Items->Item[0]->Caption =  Scards[0].name;
						Card1D->Items->Item[0]->SubItems-> Add(Scards[0].comment);
						Card2D->Items->Clear();
						Card2D->Items->Add();
						Card2D->Items->Item[0]->Caption =  Scards[1].name;
						Card2D->Items->Item[0]->SubItems-> Add(Scards[1].comment);
						Card3D->Items->Clear();
						Card3D->Items->Add();
						Card3D->Items->Item[0]->Caption =  Scards[2].name;
						Card3D->Items->Item[0]->SubItems-> Add(Scards[2].comment);
						Card4D->Items->Clear();
						Card4D->Items->Add();
						Card4D->Items->Item[0]->Caption =  Scards[3].name;
						Card4D->Items->Item[0]->SubItems-> Add(Scards[3].comment);
						Card5->Hide();
						Card6->Hide();
						Card7->Hide();
						Card8->Hide();
						Card5D->Hide();
						Card6D->Hide();
						Card7D->Hide();
						Card8D->Hide();
						return;
					case 5:
						Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[0].id);
						Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[1].id);
						Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[2].id);
						Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[3].id);
						Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[4].id);
						Card1D->Items->Clear();
						Card1D->Items->Add();
						Card1D->Items->Item[0]->Caption =  Scards[0].name;
						Card1D->Items->Item[0]->SubItems-> Add(Scards[0].comment);
						Card2D->Items->Clear();
						Card2D->Items->Add();
						Card2D->Items->Item[0]->Caption =  Scards[1].name;
						Card2D->Items->Item[0]->SubItems-> Add(Scards[1].comment);
						Card3D->Items->Clear();
						Card3D->Items->Add();
						Card3D->Items->Item[0]->Caption =  Scards[2].name;
						Card3D->Items->Item[0]->SubItems-> Add(Scards[2].comment);
						Card4D->Items->Clear();
						Card4D->Items->Add();
						Card4D->Items->Item[0]->Caption =  Scards[3].name;
						Card4D->Items->Item[0]->SubItems-> Add(Scards[3].comment);
						Card5D->Items->Clear();
						Card5D->Items->Add();
						Card5D->Items->Item[0]->Caption =  Scards[4].name;
						Card5D->Items->Item[0]->SubItems-> Add(Scards[4].comment);
						Card6->Hide();
						Card7->Hide();
						Card8->Hide();
						Card6D->Hide();
						Card7D->Hide();
						Card8D->Hide();
						return;
					case 6:
						Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[0].id);
						Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[1].id);
						Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[2].id);
						Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[3].id);
						Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[4].id);
						Card6->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[5].id);
						Card1D->Items->Clear();
						Card1D->Items->Add();
						Card1D->Items->Item[0]->Caption =  Scards[0].name;
						Card1D->Items->Item[0]->SubItems-> Add(Scards[0].comment);
						Card2D->Items->Clear();
						Card2D->Items->Add();
						Card2D->Items->Item[0]->Caption =  Scards[1].name;
						Card2D->Items->Item[0]->SubItems-> Add(Scards[1].comment);
						Card3D->Items->Clear();
						Card3D->Items->Add();
						Card3D->Items->Item[0]->Caption =  Scards[2].name;
						Card3D->Items->Item[0]->SubItems-> Add(Scards[2].comment);
						Card4D->Items->Clear();
						Card4D->Items->Add();
						Card4D->Items->Item[0]->Caption =  Scards[3].name;
						Card4D->Items->Item[0]->SubItems-> Add(Scards[3].comment);
						Card5D->Items->Clear();
						Card5D->Items->Add();
						Card5D->Items->Item[0]->Caption =  Scards[4].name;
						Card5D->Items->Item[0]->SubItems-> Add(Scards[4].comment);
						Card6D->Items->Clear();
						Card6D->Items->Add();
						Card6D->Items->Item[0]->Caption =  Scards[5].name;
						Card6D->Items->Item[0]->SubItems-> Add(Scards[5].comment);
						Card7->Hide();
						Card8->Hide();
						Card7D->Hide();
						Card8D->Hide();
						return;
					case 7:
						Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[0].id);
						Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[1].id);
						Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[2].id);
						Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[3].id);
						Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[4].id);
						Card6->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[5].id);
						Card7->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[6].id);
						Card1D->Items->Clear();
						Card1D->Items->Add();
						Card1D->Items->Item[0]->Caption =  Scards[0].name;
						Card1D->Items->Item[0]->SubItems-> Add(Scards[0].comment);
						Card2D->Items->Clear();
						Card2D->Items->Add();
						Card2D->Items->Item[0]->Caption =  Scards[1].name;
						Card2D->Items->Item[0]->SubItems-> Add(Scards[1].comment);
						Card3D->Items->Clear();
						Card3D->Items->Add();
						Card3D->Items->Item[0]->Caption =  Scards[2].name;
						Card3D->Items->Item[0]->SubItems-> Add(Scards[2].comment);
						Card4D->Items->Clear();
						Card4D->Items->Add();
						Card4D->Items->Item[0]->Caption =  Scards[3].name;
						Card4D->Items->Item[0]->SubItems-> Add(Scards[3].comment);
						Card5D->Items->Clear();
						Card5D->Items->Add();
						Card5D->Items->Item[0]->Caption =  Scards[4].name;
						Card5D->Items->Item[0]->SubItems-> Add(Scards[4].comment);
						Card6D->Items->Clear();
						Card6D->Items->Add();
						Card6D->Items->Item[0]->Caption =  Scards[5].name;
						Card6D->Items->Item[0]->SubItems-> Add(Scards[5].comment);
						Card7D->Items->Clear();
						Card7D->Items->Add();
						Card7D->Items->Item[0]->Caption =  Scards[6].name;
						Card7D->Items->Item[0]->SubItems-> Add(Scards[6].comment);
						Card8->Hide();
						Card8D->Hide();
						return;
				}
			}
			else {
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[0].id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[1].id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[2].id);
				Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[3].id);
				Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[4].id);
				Card6->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[5].id);
				Card7->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[6].id);
				Card8->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[7].id);
				if(Scards.size()==8) {
					ScrollS->Hide();
				}
				else {
					ScrollmaxS=Scards.size()/8;
				if(Scards.size()%8 != 0) {
					ScrollmaxS++;
				}
				ScrollS->Max=ScrollmaxS;
				}
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  Scards[0].name;
				Card1D->Items->Item[0]->SubItems-> Add(Scards[0].comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  Scards[1].name;
				Card2D->Items->Item[0]->SubItems-> Add(Scards[1].comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  Scards[2].name;
				Card3D->Items->Item[0]->SubItems-> Add(Scards[2].comment);
				Card4D->Items->Clear();
				Card4D->Items->Add();
				Card4D->Items->Item[0]->Caption =  Scards[3].name;
				Card4D->Items->Item[0]->SubItems-> Add(Scards[3].comment);
				Card5D->Items->Clear();
				Card5D->Items->Add();
				Card5D->Items->Item[0]->Caption =  Scards[4].name;
				Card5D->Items->Item[0]->SubItems-> Add(Scards[4].comment);
				Card6D->Items->Clear();
				Card6D->Items->Add();
				Card6D->Items->Item[0]->Caption =  Scards[5].name;
				Card6D->Items->Item[0]->SubItems-> Add(Scards[5].comment);
				Card7D->Items->Clear();
				Card7D->Items->Add();
				Card7D->Items->Item[0]->Caption =  Scards[6].name;
				Card7D->Items->Item[0]->SubItems-> Add(Scards[6].comment);
				Card8D->Items->Clear();
				Card8D->Items->Add();
				Card8D->Items->Item[0]->Caption =  Scards[7].name;
				Card8D->Items->Item[0]->SubItems-> Add(Scards[7].comment);
			}
		}
	}
	else {
		ScrollS->Hide();
		Scroll->OnChange(Form2);
		Scroll->Show();
        Scroll->Position=1;
	}
	Scards.clear();
}
void __fastcall TForm2::ScrollSChange(TObject *Sender)
{
	MyCards=LoadLibraryA("cards.dll");
	 if(!MyCards) {
		 ShowMessage("cards not found");
		 return;
	 }
	_di_IXMLcollectedType User = Getcollected(Xuser);
	Card1->Show();
	Card2->Show();
	Card3->Show();
	Card4->Show();
	Card5->Show();
	Card6->Show();
	Card7->Show();
	Card8->Show();
	Card1D->Show();
	Card2D->Show();
	Card3D->Show();
	Card4D->Show();
	Card5D->Show();
	Card6D->Show();
	Card7D->Show();
	Card8D->Show();
    std::vector<Card>Scards;
	for(int i=0;i<User->Count;i++) {
		if(User->card[i]->comment != "Basic") {
			Card temp;
			temp.id=User->card[i]->id;
			temp.name=User->card[i]->name;
			temp.comment=User->card[i]->comment;
			Scards.push_back(temp);
		}
	}
	int condition=Scards.size()%8;
	if(ScrollS->Position==ScrollmaxS) {
		switch (condition) {
			case 0:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-8].id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-7].id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-6].id);
				Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-5].id);
				Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-4].id);
				Card6->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-3].id);
				Card7->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-2].id);
				Card8->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-1].id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-8].name;
				Card1D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-8].comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-7].name;
				Card2D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-7].comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-6].name;
				Card3D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-6].comment);
				Card4D->Items->Clear();
				Card4D->Items->Add();
				Card4D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-5].name;
				Card4D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-5].comment);
				Card5D->Items->Clear();
				Card5D->Items->Add();
				Card5D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-4].name;
				Card5D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-4].comment);
				Card6D->Items->Clear();
				Card6D->Items->Add();
				Card6D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-3].name;
				Card6D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-3].comment);
				Card7D->Items->Clear();
				Card7D->Items->Add();
				Card7D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-2].name;
				Card7D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-2].comment);
				Card8D->Items->Clear();
				Card8D->Items->Add();
				Card8D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-1].name;
				Card8D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-1].comment);
				return;
			case 1:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-8].id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-8].name;
				Card1D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-8].comment);
				Card2->Hide();
				Card3->Hide();
				Card4->Hide();
				Card5->Hide();
				Card6->Hide();
				Card7->Hide();
				Card8->Hide();
				Card2D->Hide();
				Card3D->Hide();
				Card4D->Hide();
				Card5D->Hide();
				Card6D->Hide();
				Card7D->Hide();
				Card8D->Hide();
				return;
			case 2:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-8].id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-7].id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption=Scards[ScrollS->Position*8-8].name;
				Card1D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-8].comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =   Scards[ScrollS->Position*8-7].name;
				Card2D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-7].comment);
				Card3->Hide();
				Card4->Hide();
				Card5->Hide();
				Card6->Hide();
				Card7->Hide();
				Card8->Hide();
				Card3D->Hide();
				Card4D->Hide();
				Card5D->Hide();
				Card6D->Hide();
				Card7D->Hide();
				Card8D->Hide();
				return;
			case 3:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-8].id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-7].id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-6].id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-8].name;
				Card1D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-8].comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-7].name;
				Card2D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-7].comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-6].name;
				Card3D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-6].comment);
				Card4->Hide();
				Card5->Hide();
				Card6->Hide();
				Card7->Hide();
				Card8->Hide();
				Card4D->Hide();
				Card5D->Hide();
				Card6D->Hide();
				Card7D->Hide();
				Card8D->Hide();
				return;
			case 4:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-8].id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-7].id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-6].id);
				Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-5].id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-8].name;
				Card1D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-8].comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-7].name;
				Card2D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-7].comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-6].name;
				Card3D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-6].comment);
				Card4D->Items->Clear();
				Card4D->Items->Add();
				Card4D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-5].name;
				Card4D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-5].comment);
				Card5->Hide();
				Card6->Hide();
				Card7->Hide();
				Card8->Hide();
				Card5D->Hide();
				Card6D->Hide();
				Card7D->Hide();
				Card8D->Hide();
				return;
			case 5:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-8].id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-7].id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-6].id);
				Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-5].id);
				Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-4].id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-8].name;
				Card1D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-8].comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-7].name;
				Card2D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-7].comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-6].name;
				Card3D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-6].comment);
				Card4D->Items->Clear();
				Card4D->Items->Add();
				Card4D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-5].name;
				Card4D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-5].comment);
				Card5D->Items->Clear();
				Card5D->Items->Add();
				Card5D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-4].name;
				Card5D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-4].comment);
				Card6->Hide();
				Card7->Hide();
				Card8->Hide();
				Card6D->Hide();
				Card7D->Hide();
				Card8D->Hide();
				return;
			case 6:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-8].id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-7].id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-6].id);
				Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-5].id);
				Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-4].id);
				Card6->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-3].id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-8].name;
				Card1D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-8].comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-7].name;
				Card2D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-7].comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-6].name;
				Card3D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-6].comment);
				Card4D->Items->Clear();
				Card4D->Items->Add();
				Card4D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-5].name;
				Card4D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-5].comment);
				Card5D->Items->Clear();
				Card5D->Items->Add();
				Card5D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-4].name;
				Card5D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-4].comment);
				Card6D->Items->Clear();
				Card6D->Items->Add();
				Card6D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-3].name;
				Card6D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-3].comment);
				Card7->Hide();
				Card8->Hide();
				Card7D->Hide();
				Card8D->Hide();
				return;
			case 7:
				Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-8].id);
				Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-7].id);
				Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-6].id);
				Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-5].id);
				Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-4].id);
				Card6->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-3].id);
				Card7->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-2].id);
				Card1D->Items->Clear();
				Card1D->Items->Add();
				Card1D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-8].name;
				Card1D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-8].comment);
				Card2D->Items->Clear();
				Card2D->Items->Add();
				Card2D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-7].name;
				Card2D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-7].comment);
				Card3D->Items->Clear();
				Card3D->Items->Add();
				Card3D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-6].name;
				Card3D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-6].comment);
				Card4D->Items->Clear();
				Card4D->Items->Add();
				Card4D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-5].name;
				Card4D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-5].comment);
				Card5D->Items->Clear();
				Card5D->Items->Add();
				Card5D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-4].name;
				Card5D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-4].comment);
				Card6D->Items->Clear();
				Card6D->Items->Add();
				Card6D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-3].name;
				Card6D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-3].comment);
				Card7D->Items->Clear();
				Card7D->Items->Add();
				Card7D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-2].name;
				Card7D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-2].comment);
				Card8->Hide();
				Card8D->Hide();
				return;
		}
	}
	else {
		Card1->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-8].id);
		Card2->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-7].id);
		Card3->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-6].id);
		Card4->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-5].id);
		Card5->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-4].id);
		Card6->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-3].id);
		Card7->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-2].id);
		Card8->Picture->Bitmap->LoadFromResourceID((unsigned)MyCards, Scards[ScrollS->Position*8-1].id);
		Card1D->Items->Clear();
		Card1D->Items->Add();
		Card1D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-8].name;
		Card1D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-8].comment);
		Card2D->Items->Clear();
		Card2D->Items->Add();
		Card2D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-7].name;
		Card2D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-7].comment);
		Card3D->Items->Clear();
		Card3D->Items->Add();
		Card3D->Items->Item[0]->Caption = Scards[ScrollS->Position*8-6].name;
		Card3D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-6].comment);
		Card4D->Items->Clear();
		Card4D->Items->Add();
		Card4D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-5].name;
		Card4D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-5].comment);
		Card5D->Items->Clear();
		Card5D->Items->Add();
		Card5D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-4].name;
		Card5D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-4].comment);
		Card6D->Items->Clear();
		Card6D->Items->Add();
		Card6D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-3].name;
		Card6D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-3].comment);
		Card7D->Items->Clear();
		Card7D->Items->Add();
		Card7D->Items->Item[0]->Caption =  Scards[ScrollS->Position*8-2].name;
		Card7D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-2].comment);
		Card8D->Items->Clear();
		Card8D->Items->Add();
		Card8D->Items->Item[0]->Caption = Scards[ScrollS->Position*8-1].name;
		Card8D->Items->Item[0]->SubItems-> Add(Scards[ScrollS->Position*8-1].comment);
	}
	Scards.clear();
}
void __fastcall TForm2::FormClose(TObject *Sender, TCloseAction &Action)
{
	FreeLibrary(MyCards);
}

